apiVersion: apps/v1
kind: Deployment
metadata:
  name: claims-agent
  namespace: cursor-insurance-ai-poc
  labels:
    app: claims-agent
    component: domain-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: claims-agent
  template:
    metadata:
      labels:
        app: claims-agent
        component: domain-agent
    spec:
      containers:
      - name: claims-agent
        image: insurance-ai/claims-agent:latest
        ports:
        - containerPort: 8000
        env:
        - name: CLAIMS_AGENT_PORT
          value: "8000"
        - name: DATA_AGENT_URL
          value: "http://data-agent:8002"
        - name: NOTIFICATION_AGENT_URL
          value: "http://notification-agent:8003"
        - name: INTEGRATION_AGENT_URL
          value: "http://integration-agent:8004"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: llm-secrets
              key: openai-api-key
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: llm-secrets
              key: anthropic-api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: claims-agent
  namespace: cursor-insurance-ai-poc
  labels:
    app: claims-agent
spec:
  selector:
    app: claims-agent
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-agent
  namespace: cursor-insurance-ai-poc
  labels:
    app: data-agent
    component: technical-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-agent
  template:
    metadata:
      labels:
        app: data-agent
        component: technical-agent
    spec:
      containers:
      - name: data-agent
        image: insurance-ai/data-agent:latest
        ports:
        - containerPort: 8002
        env:
        - name: DATA_AGENT_PORT
          value: "8002"
        - name: CLAIMS_API_URL
          value: "http://claims-service:8000"
        - name: USER_API_URL
          value: "http://user-service:8000"
        - name: POLICY_API_URL
          value: "http://policy-service:8000"
        - name: ANALYTICS_API_URL
          value: "http://analytics-service:8000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: data-agent
  namespace: cursor-insurance-ai-poc
  labels:
    app: data-agent
spec:
  selector:
    app: data-agent
  ports:
  - port: 8002
    targetPort: 8002
    protocol: TCP
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-agent
  namespace: cursor-insurance-ai-poc
  labels:
    app: notification-agent
    component: technical-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-agent
  template:
    metadata:
      labels:
        app: notification-agent
        component: technical-agent
    spec:
      containers:
      - name: notification-agent
        image: insurance-ai/notification-agent:latest
        ports:
        - containerPort: 8003
        env:
        - name: NOTIFICATION_AGENT_PORT
          value: "8003"
        - name: OPS_PHONE
          value: "+1234567890"
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8003
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: notification-agent
  namespace: cursor-insurance-ai-poc
  labels:
    app: notification-agent
spec:
  selector:
    app: notification-agent
  ports:
  - port: 8003
    targetPort: 8003
    protocol: TCP
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: claims-service
  namespace: cursor-insurance-ai-poc
  labels:
    app: claims-service
    component: enterprise-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: claims-service
  template:
    metadata:
      labels:
        app: claims-service
        component: enterprise-service
    spec:
      containers:
      - name: claims-service
        image: insurance-ai/claims-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: SERVICE_PORT
          value: "8000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: claims-db-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: claims-service
  namespace: cursor-insurance-ai-poc
  labels:
    app: claims-service
spec:
  selector:
    app: claims-service
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: cursor-insurance-ai-poc
  labels:
    app: user-service
    component: enterprise-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        component: enterprise-service
    spec:
      containers:
      - name: user-service
        image: insurance-ai/user-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: SERVICE_PORT
          value: "8000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: user-db-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "512Mi"
            cpu: "300m"

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: cursor-insurance-ai-poc
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-service
  namespace: cursor-insurance-ai-poc
  labels:
    app: policy-service
    component: enterprise-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: policy-service
  template:
    metadata:
      labels:
        app: policy-service
        component: enterprise-service
    spec:
      containers:
      - name: policy-service
        image: insurance-ai/policy-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: SERVICE_PORT
          value: "8000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: policy-db-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "512Mi"
            cpu: "300m"

---
apiVersion: v1
kind: Service
metadata:
  name: policy-service
  namespace: cursor-insurance-ai-poc
  labels:
    app: policy-service
spec:
  selector:
    app: policy-service
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: cursor-insurance-ai-poc
  labels:
    app: analytics-service
    component: enterprise-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
        component: enterprise-service
    spec:
      containers:
      - name: analytics-service
        image: insurance-ai/analytics-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: SERVICE_PORT
          value: "8000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: analytics-db-url
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: cursor-insurance-ai-poc
  labels:
    app: analytics-service
spec:
  selector:
    app: analytics-service
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-ui
  namespace: cursor-insurance-ai-poc
  labels:
    app: insurance-ui
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insurance-ui
  template:
    metadata:
      labels:
        app: insurance-ui
        component: frontend
    spec:
      containers:
      - name: insurance-ui
        image: insurance-ai/insurance-ui:latest
        ports:
        - containerPort: 8501
        env:
        - name: STREAMLIT_SERVER_PORT
          value: "8501"
        - name: CLAIMS_AGENT_URL
          value: "http://claims-agent:8000"
        - name: DATA_AGENT_URL
          value: "http://data-agent:8002"
        - name: NOTIFICATION_AGENT_URL
          value: "http://notification-agent:8003"
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "512Mi"
            cpu: "300m"

---
apiVersion: v1
kind: Service
metadata:
  name: insurance-ui
  namespace: cursor-insurance-ai-poc
  labels:
    app: insurance-ui
spec:
  selector:
    app: insurance-ui
  ports:
  - port: 8501
    targetPort: 8501
    protocol: TCP
  type: LoadBalancer 