# Default values for insurance-ai-poc
replicaCount: 1

image:
  repository: insurance-ai-poc
  tag: fix-1748660643
  pullPolicy: Never

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

# Domain Agent Configuration
domainAgent:
  enabled: true
  port: 8003
  replicas: 2
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Technical Agent Configuration  
technicalAgent:
  enabled: true
  port: 8002
  replicas: 2
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Policy Server Configuration
policyServer:
  enabled: true
  port: 8001
  replicas: 2
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 150m
      memory: 128Mi

# Streamlit UI Configuration
streamlitUI:
  enabled: true
  port: 8501
  replicas: 1
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 150m
      memory: 256Mi

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: insurance-ai.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Environment variables
env:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  OPENAI_API_KEY: ""
  ANTHROPIC_API_KEY: ""
  
# ConfigMap for application configuration
config:
  domainAgent:
    host: "0.0.0.0"
    port: 8003
    technicalAgentUrl: "http://insurance-ai-poc-technical-agent:8002"
    policyServerUrl: "http://insurance-ai-poc-policy-server:8001"
  
  technicalAgent:
    host: "0.0.0.0" 
    port: 8002
    policyServerUrl: "http://insurance-ai-poc-policy-server:8001"
    
  policyServer:
    host: "0.0.0.0"
    port: 8001
    dataPath: "/app/data"
    
  streamlitUI:
    host: "0.0.0.0"
    port: 8501
    domainAgentUrl: "http://insurance-ai-poc-domain-agent:8003"

# Force deployment update
deploymentUpdate:
  timestamp: "2025-05-31-00-26" 