[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "analytics-service"
version = "1.0.0"
description = "Analytics service with FastAPI"
dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic",
    "prometheus-client",
    "PyJWT",
] 