apiVersion: v1
kind: Namespace
metadata:
  name: cursor-insurance-ai-poc
  labels:
    name: cursor-insurance-ai-poc

---
apiVersion: v1
kind: Secret
metadata:
  name: llm-secrets
  namespace: cursor-insurance-ai-poc
type: Opaque
data:
  # Base64 encoded values - using actual API keys
  # echo -n "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" | base64
  openai-api-key: c2stb3ItdjEtZGMyNGEwM2U4ZjhmNTNlMzBjZDExZWQwYTRiN2JiMTQ1OGUzMmY4MDM5MmE2OGI3ZTZkMTk4ZDg5OGE5MGFkZg==
  # Using OpenRouter key for Anthropic as well since it supports Claude
  anthropic-api-key: c2stb3ItdjEtZGMyNGEwM2U4ZjhmNTNlMzBjZDExZWQwYTRiN2JiMTQ1OGUzMmY4MDM5MmE2OGI3ZTZkMTk4ZDg5OGE5MGFkZg==
  # OpenRouter API key
  openrouter-api-key: c2stb3ItdjEtZGMyNGEwM2U4ZjhmNTNlMzBjZDExZWQwYTRiN2JiMTQ1OGUzMmY4MDM5MmE2OGI3ZTZkMTk4ZDg5OGE5MGFkZg==

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: cursor-insurance-ai-poc
type: Opaque
data:
  # Base64 encoded database URLs - using SQLite for demo
  # echo -n "sqlite:///app/data/claims.db" | base64
  claims-db-url: c3FsaXRlOi8vL2FwcC9kYXRhL2NsYWltcy5kYg==
  user-db-url: c3FsaXRlOi8vL2FwcC9kYXRhL3VzZXJzLmRi
  policy-db-url: c3FsaXRlOi8vL2FwcC9kYXRhL3BvbGljaWVzLmRi
  analytics-db-url: c3FsaXRlOi8vL2FwcC9kYXRhL2FuYWx5dGljcy5kYg==

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: insurance-config
  namespace: cursor-insurance-ai-poc
data:
  # Agent configuration
  log_level: "INFO"
  a2a_protocol_version: "1.0"
  mcp_protocol_version: "1.0"
  
  # Service discovery
  service_registry_url: "http://consul:8500"
  
  # Monitoring configuration
  prometheus_enabled: "true"
  jaeger_enabled: "true"
  
  # Feature flags
  fraud_detection_enabled: "true"
  llm_fallback_enabled: "true"
  cache_enabled: "true"
  
  # Performance settings
  request_timeout: "30"
  max_connections: "100"
  connection_pool_size: "10" 