[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "insurance-ui"
version = "1.0.0" 
description = "Streamlit UI for insurance AI agent interaction"
dependencies = [
    "streamlit",
    "streamlit-autorefresh",
    "plotly",
    "altair",
    "pandas",
    "requests",
    "httpx",
] 