{{- if .Values.domainAgent.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "insurance-ai-poc.fullname" . }}-domain-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "insurance-ai-poc.labels" . | nindent 4 }}
    component: domain-agent
spec:
  replicas: {{ .Values.domainAgent.replicas }}
  selector:
    matchLabels:
      {{- include "insurance-ai-poc.selectorLabels" . | nindent 6 }}
      component: domain-agent
  template:
    metadata:
      annotations:
        deployment-update: {{ .Values.deploymentUpdate.timestamp | quote }}
      labels:
        {{- include "insurance-ai-poc.selectorLabels" . | nindent 8 }}
        component: domain-agent
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "insurance-ai-poc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: domain-agent
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.domainAgent.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "insurance-ai-poc.fullname" . }}-config
          env:
            {{- if .Values.secrets.useExistingSecret }}
            # Use existing Kubernetes secret (recommended for production)
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.secretName }}
                  key: OPENAI_API_KEY
            - name: OPENROUTER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.secretName }}
                  key: OPENROUTER_API_KEY
                  optional: true
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.secretName }}
                  key: ANTHROPIC_API_KEY
                  optional: true
            # Monitoring secrets
            - name: LANGFUSE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.secretName }}
                  key: LANGFUSE_SECRET_KEY
                  optional: true
            - name: LANGFUSE_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.secretName }}
                  key: LANGFUSE_PUBLIC_KEY
                  optional: true
            - name: PROMETHEUS_GATEWAY_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.secretName }}
                  key: PROMETHEUS_GATEWAY_URL
                  optional: true
            - name: GRAFANA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.secretName }}
                  key: GRAFANA_API_KEY
                  optional: true
            {{- else }}
            # Fallback to values (backward compatibility, not recommended for production)
            - name: OPENAI_API_KEY
              value: {{ .Values.env.OPENAI_API_KEY | default .Values.secrets.apiKeys.openaiApiKey | quote }}
            - name: OPENROUTER_API_KEY
              value: {{ .Values.env.OPENROUTER_API_KEY | default .Values.secrets.apiKeys.openrouterApiKey | quote }}
            - name: ANTHROPIC_API_KEY
              value: {{ .Values.env.ANTHROPIC_API_KEY | default .Values.secrets.apiKeys.anthropicApiKey | quote }}
            # Monitoring environment variables
            - name: LANGFUSE_SECRET_KEY
              value: {{ .Values.monitoring.langfuse.secretKey | default "" | quote }}
            - name: LANGFUSE_PUBLIC_KEY
              value: {{ .Values.monitoring.langfuse.publicKey | default "" | quote }}
            - name: LANGFUSE_HOST
              value: {{ .Values.monitoring.langfuse.host | default "https://cloud.langfuse.com" | quote }}
            - name: PROMETHEUS_GATEWAY_URL
              value: {{ .Values.monitoring.prometheus.gatewayUrl | default "" | quote }}
            - name: PROMETHEUS_JOB_NAME
              value: {{ .Values.monitoring.prometheus.jobName | default "insurance-ai-domain-agent" | quote }}
            - name: GRAFANA_API_KEY
              value: {{ .Values.monitoring.grafana.apiKey | default "" | quote }}
            {{- end }}
            # Common monitoring environment variables
            - name: ENVIRONMENT
              value: {{ .Values.environment | default "development" | quote }}
            - name: SERVICE_NAME
              value: "domain-agent"
            - name: SERVICE_VERSION
              value: {{ .Chart.AppVersion | quote }}
          workingDir: /app
          command: ["python", "domain_agent/main.py"]
          resources:
            {{- toYaml .Values.domainAgent.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 