{{- if .Values.policyServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "insurance-ai-poc.fullname" . }}-policy-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "insurance-ai-poc.labels" . | nindent 4 }}
    component: policy-server
spec:
  replicas: {{ .Values.policyServer.replicas }}
  selector:
    matchLabels:
      {{- include "insurance-ai-poc.selectorLabels" . | nindent 6 }}
      component: policy-server
  template:
    metadata:
      labels:
        {{- include "insurance-ai-poc.selectorLabels" . | nindent 8 }}
        component: policy-server
    spec:
      serviceAccountName: {{ include "insurance-ai-poc.serviceAccountName" . }}
      containers:
        - name: policy-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.policyServer.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "insurance-ai-poc.fullname" . }}-config
          workingDir: /app
          command: ["python", "policy_server/main.py"]
          resources:
            {{- toYaml .Values.policyServer.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 