{{- if .Values.policyServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "insurance-ai-poc.fullname" . }}-policy-server
  namespace: insurance-ai-agentic
  labels:
    {{- include "insurance-ai-poc.labels" . | nindent 4 }}
    component: policy-server
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.policyServer.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "insurance-ai-poc.selectorLabels" . | nindent 4 }}
    component: policy-server
{{- end }} 