{{- if .Values.streamlitUI.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "insurance-ai-poc.fullname" . }}-streamlit-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "insurance-ai-poc.labels" . | nindent 4 }}
    component: streamlit-ui
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "insurance-ai-poc.selectorLabels" . | nindent 4 }}
    component: streamlit-ui
{{- end }} 