{{- if .Values.technicalAgent.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "insurance-ai-poc.fullname" . }}-technical-agent
  namespace: insurance-ai-agentic
  labels:
    {{- include "insurance-ai-poc.labels" . | nindent 4 }}
    component: technical-agent
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.technicalAgent.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "insurance-ai-poc.selectorLabels" . | nindent 4 }}
    component: technical-agent
{{- end }} 