{{- if .Values.technicalAgent.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "insurance-ai-poc.fullname" . }}-technical-agent
  namespace: insurance-ai-agentic
  labels:
    {{- include "insurance-ai-poc.labels" . | nindent 4 }}
    component: technical-agent
spec:
  replicas: {{ .Values.technicalAgent.replicas }}
  selector:
    matchLabels:
      {{- include "insurance-ai-poc.selectorLabels" . | nindent 6 }}
      component: technical-agent
  template:
    metadata:
      labels:
        {{- include "insurance-ai-poc.selectorLabels" . | nindent 8 }}
        component: technical-agent
    spec:
      serviceAccountName: {{ include "insurance-ai-poc.serviceAccountName" . }}
      containers:
        - name: technical-agent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.technicalAgent.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "insurance-ai-poc.fullname" . }}-config
          env:
            - name: OPENAI_API_KEY
              value: {{ .Values.env.OPENAI_API_KEY | quote }}
            - name: ANTHROPIC_API_KEY
              value: {{ .Values.env.ANTHROPIC_API_KEY | quote }}
          workingDir: /app
          command: ["python", "technical_agent/main.py"]
          resources:
            {{- toYaml .Values.technicalAgent.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 