name: 'Docker Build & Push'
description: 'Build and optionally push Docker images with caching'

inputs:
  push:
    description: 'Whether to push to registry'
    required: false
    default: 'true'
  tags:
    description: 'Docker image tags (comma-separated)'
    required: true
  labels:
    description: 'Docker image labels'
    required: false
    default: ''
  platforms:
    description: 'Target platforms for build'
    required: false
    default: 'linux/amd64'
  context:
    description: 'Build context path'
    required: false
    default: '.'

outputs:
  digest:
    description: 'Image digest'
    value: ${{ steps.build.outputs.digest }}
  metadata:
    description: 'Build metadata'
    value: ${{ steps.build.outputs.metadata }}

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true
        
    - name: Log in to Container Registry
      if: inputs.push == 'true'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    
    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        push: ${{ inputs.push }}
        tags: ${{ inputs.tags }}
        labels: ${{ inputs.labels }}
        platforms: ${{ inputs.platforms }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        provenance: false  # Disable provenance for better compatibility
        
    - name: Generate build summary
      shell: bash
      run: |
        echo "### ðŸ³ Docker Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Tags:** ${{ inputs.tags }}" >> $GITHUB_STEP_SUMMARY
        echo "**Platforms:** ${{ inputs.platforms }}" >> $GITHUB_STEP_SUMMARY
        echo "**Push:** ${{ inputs.push }}" >> $GITHUB_STEP_SUMMARY
        if [[ "${{ inputs.push }}" == "true" ]]; then
          echo "**Digest:** ${{ steps.build.outputs.digest }}" >> $GITHUB_STEP_SUMMARY
        fi 