apiVersion: apps/v1
kind: Deployment
metadata:
  name: claims-agent
  namespace: insurance-poc
  labels:
    app: claims-agent
    component: domain-agent
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: claims-agent
  template:
    metadata:
      labels:
        app: claims-agent
        component: domain-agent
        version: v1
    spec:
      containers:
      - name: claims-agent
        image: insurance-ai-poc:latest
        imagePullPolicy: IfNotPresent
        command:
          - python
          - -m
          - agents.domain.claims_domain_agent
        ports:
        - containerPort: 8007
          name: http
          protocol: TCP
        env:
        - name: CLAIMS_DOMAIN_AGENT_PORT
          value: "8007"
        envFrom:
        - configMapRef:
            name: agent-config
        - secretRef:
            name: llm-api-keys
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8007
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8007
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8007
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 10

---
apiVersion: v1
kind: Service
metadata:
  name: claims-agent
  namespace: insurance-poc
  labels:
    app: claims-agent
    component: domain-agent
spec:
  type: ClusterIP
  selector:
    app: claims-agent
  ports:
  - port: 8007
    targetPort: 8007
    protocol: TCP
    name: http

---
apiVersion: v1
kind: Service
metadata:
  name: claims-agent-nodeport
  namespace: insurance-poc
  labels:
    app: claims-agent
    component: domain-agent
spec:
  type: NodePort
  selector:
    app: claims-agent
  ports:
  - port: 8007
    targetPort: 8007
    nodePort: 30008
    protocol: TCP
    name: http 