apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-service-config
  namespace: insurance-poc
  labels:
    app: customer-service
    component: backend-service
data:
  CUSTOMER_SERVICE_PORT: "8000"
  LOG_LEVEL: "INFO"
  DEBUG: "false"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  namespace: insurance-poc
  labels:
    app: customer-service
    component: backend-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
        component: backend-service
        version: v1
    spec:
      containers:
      - name: customer-service
        image: insurance-ai-poc:latest
        imagePullPolicy: IfNotPresent
        command:
          - python
          - -m
          - uvicorn
          - services.customer.app:app
          - --host
          - "0.0.0.0"
          - --port
          - "8000"
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        - name: CUSTOMER_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: customer-service-config
              key: CUSTOMER_SERVICE_PORT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: customer-service-config
              key: LOG_LEVEL
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: customer-service-config
              key: DEBUG
        - name: PYTHONPATH
          value: "/app"
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 10

---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: insurance-poc
  labels:
    app: customer-service
    component: backend-service
spec:
  type: ClusterIP
  selector:
    app: customer-service
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http

---
apiVersion: v1
kind: Service
metadata:
  name: customer-service-nodeport
  namespace: insurance-poc
  labels:
    app: customer-service
    component: backend-service
spec:
  type: NodePort
  selector:
    app: customer-service
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000
    protocol: TCP
    name: http