---
# ConfigMap for mock data
apiVersion: v1
kind: ConfigMap
metadata:
  name: mock-data-config
  namespace: insurance-ai-poc
data:
  mock_data.json: |
    {
      "policies": [
        {
          "policy_id": "POL001",
          "customer_id": "CUST001", 
          "policy_type": "Auto",
          "premium": 1200.00,
          "deductible": 500,
          "coverage_limits": {
            "liability": 100000,
            "collision": 50000,
            "comprehensive": 25000
          },
          "status": "active",
          "effective_date": "2024-01-01",
          "expiry_date": "2025-01-01"
        },
        {
          "policy_id": "POL002", 
          "customer_id": "CUST002",
          "policy_type": "Home",
          "premium": 2400.00,
          "deductible": 1000,
          "coverage_limits": {
            "dwelling": 300000,
            "personal_property": 150000,
            "liability": 500000
          },
          "status": "active",
          "effective_date": "2024-02-01",
          "expiry_date": "2025-02-01"
        },
        {
          "policy_id": "POL003",
          "customer_id": "CUST003", 
          "policy_type": "Life",
          "premium": 600.00,
          "deductible": 0,
          "coverage_limits": {
            "death_benefit": 500000,
            "cash_value": 50000
          },
          "status": "active",
          "effective_date": "2024-03-01",
          "expiry_date": "2034-03-01"
        },
        {
          "policy_id": "POL004",
          "customer_id": "CUST001", 
          "policy_type": "Home",
          "premium": 1800.00,
          "deductible": 750,
          "coverage_limits": {
            "dwelling": 250000,
            "personal_property": 100000,
            "liability": 300000
          },
          "status": "active",
          "effective_date": "2024-01-15",
          "expiry_date": "2025-01-15"
        },
        {
          "policy_id": "POL005",
          "customer_id": "CUST004", 
          "policy_type": "Auto",
          "premium": 900.00,
          "deductible": 250,
          "coverage_limits": {
            "liability": 75000,
            "collision": 30000,
            "comprehensive": 15000
          },
          "status": "active",
          "effective_date": "2024-04-01",
          "expiry_date": "2025-04-01"
        }
      ],
      "customers": [
        {
          "customer_id": "CUST001",
          "name": "John Smith",
          "email": "john.smith@email.com",
          "phone": "+1-555-0123",
          "address": {
            "street": "123 Main St",
            "city": "Anytown", 
            "state": "NY",
            "zip": "12345"
          },
          "date_of_birth": "1985-06-15",
          "policies": ["POL001", "POL004"]
        },
        {
          "customer_id": "CUST002",
          "name": "Jane Doe",
          "email": "jane.doe@email.com", 
          "phone": "+1-555-0456",
          "address": {
            "street": "456 Oak Ave",
            "city": "Somewhere",
            "state": "CA", 
            "zip": "90210"
          },
          "date_of_birth": "1990-03-22",
          "policies": ["POL002"]
        },
        {
          "customer_id": "CUST003",
          "name": "Bob Johnson",
          "email": "bob.johnson@email.com",
          "phone": "+1-555-0789", 
          "address": {
            "street": "789 Pine Dr",
            "city": "Elsewhere",
            "state": "TX",
            "zip": "75201"
          },
          "date_of_birth": "1975-11-08",
          "policies": ["POL003"]
        },
        {
          "customer_id": "CUST004",
          "name": "Alice Williams",
          "email": "alice.williams@email.com",
          "phone": "+1-555-0321", 
          "address": {
            "street": "321 Elm St",
            "city": "Newtown",
            "state": "FL",
            "zip": "33101"
          },
          "date_of_birth": "1988-09-12",
          "policies": ["POL005"]
        }
      ],
      "claims": [
        {
          "claim_id": "CLM001",
          "policy_id": "POL001",
          "customer_id": "CUST001",
          "claim_type": "collision",
          "incident_date": "2024-05-15",
          "reported_date": "2024-05-16", 
          "status": "under_review",
          "amount_claimed": 8500.00,
          "amount_approved": 0,
          "description": "Rear-end collision at intersection"
        },
        {
          "claim_id": "CLM002",
          "policy_id": "POL002", 
          "customer_id": "CUST002",
          "claim_type": "water_damage",
          "incident_date": "2024-04-20",
          "reported_date": "2024-04-21",
          "status": "approved",
          "amount_claimed": 15000.00,
          "amount_approved": 12000.00,
          "description": "Burst pipe caused water damage to living room"
        },
        {
          "claim_id": "CLM003",
          "policy_id": "POL004", 
          "customer_id": "CUST001",
          "claim_type": "theft",
          "incident_date": "2024-06-01",
          "reported_date": "2024-06-01",
          "status": "approved",
          "amount_claimed": 5000.00,
          "amount_approved": 4500.00,
          "description": "Stolen personal property from home"
        }
      ],
      "agents": [
        {
          "agent_id": "AGT001",
          "name": "Sarah Wilson",
          "email": "sarah.wilson@insurance.com",
          "phone": "+1-555-1001", 
          "territory": "Northeast",
          "customers": ["CUST001", "CUST003"]
        },
        {
          "agent_id": "AGT002",
          "name": "Mike Chen", 
          "email": "mike.chen@insurance.com",
          "phone": "+1-555-1002",
          "territory": "West Coast",
          "customers": ["CUST002"]
        },
        {
          "agent_id": "AGT003",
          "name": "Lisa Rodriguez", 
          "email": "lisa.rodriguez@insurance.com",
          "phone": "+1-555-1003",
          "territory": "Southeast",
          "customers": ["CUST004"]
        }
      ],
      "metadata": {
        "version": "1.1.0",
        "last_updated": "2024-06-11T00:00:00Z",
        "total_policies": 5,
        "total_customers": 4,
        "total_claims": 3,
        "total_agents": 3
      }
    }

---
# Policy Server Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-server
  namespace: insurance-ai-poc
  labels:
    app: policy-server
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy-server
  template:
    metadata:
      labels:
        app: policy-server
        component: backend
    spec:
      containers:
      - name: policy-server
        image: insurance-ai-poc:latest
        imagePullPolicy: IfNotPresent
        workingDir: /app/policy_server
        command: ["python", "main.py"]
        ports:
        - containerPort: 8001
          name: http
        env:
        - name: PORT
          value: "8001"
        - name: HOST
          value: "0.0.0.0"
        volumeMounts:
        - name: mock-data
          mountPath: /app/data
          readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: mock-data
        configMap:
          name: mock-data-config

---
# Policy Server Service
apiVersion: v1
kind: Service
metadata:
  name: policy-server
  namespace: insurance-ai-poc
  labels:
    app: policy-server
spec:
  type: ClusterIP
  selector:
    app: policy-server
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http

---
# Streamlit UI Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-ui
  namespace: insurance-ai-poc
  labels:
    app: streamlit-ui
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-ui
  template:
    metadata:
      labels:
        app: streamlit-ui
        component: frontend
    spec:
      containers:
      - name: streamlit-ui
        image: insurance-ai-poc:latest
        imagePullPolicy: IfNotPresent
        workingDir: /app/ui
        command: ["streamlit", "run", "main_ui.py", "--server.port=8501", "--server.address=0.0.0.0"]
        ports:
        - containerPort: 8501
          name: http
        env:
        - name: POLICY_SERVER_URL
          value: "http://adk-customer-service:8000"
        - name: ADK_CUSTOMER_SERVICE_URL
          value: "http://adk-customer-service:8000"
        - name: UI_MODE
          value: "advanced"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10

---
# Streamlit UI Service
apiVersion: v1
kind: Service
metadata:
  name: streamlit-ui
  namespace: insurance-ai-poc
  labels:
    app: streamlit-ui
spec:
  type: ClusterIP
  selector:
    app: streamlit-ui
  ports:
  - port: 8501
    targetPort: 8501
    protocol: TCP
    name: http

---
# ADK Customer Service Agent Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adk-customer-service
  namespace: insurance-ai-poc
  labels:
    app: adk-customer-service
    component: adk-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adk-customer-service
  template:
    metadata:
      labels:
        app: adk-customer-service
        component: adk-agent
    spec:
      containers:
      - name: adk-customer-service
        image: insurance-ai-poc:latest
        imagePullPolicy: IfNotPresent
        workingDir: /app/insurance-adk
        command: ["python", "-m", "google.adk.cli", "web", "insurance_customer_service", "--port", "8000", "--host", "0.0.0.0"]
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: GOOGLE_API_KEY
          value: "test_placeholder"
        - name: PORT
          value: "8000"
        - name: HOST
          value: "0.0.0.0"
        - name: TECHNICAL_AGENT_URL
          value: "http://adk-technical-agent:8002"
        - name: ORCHESTRATOR_URL
          value: "http://adk-orchestrator:8003"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"

---
# ADK Customer Service Service
apiVersion: v1
kind: Service
metadata:
  name: adk-customer-service
  namespace: insurance-ai-poc
  labels:
    app: adk-customer-service
spec:
  type: ClusterIP
  selector:
    app: adk-customer-service
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http

---
# ADK Technical Agent Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adk-technical-agent
  namespace: insurance-ai-poc
  labels:
    app: adk-technical-agent
    component: adk-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adk-technical-agent
  template:
    metadata:
      labels:
        app: adk-technical-agent
        component: adk-agent
    spec:
      containers:
      - name: adk-technical-agent
        image: insurance-ai-poc:latest
        imagePullPolicy: IfNotPresent
        workingDir: /app/insurance-adk
        command: ["python", "-m", "google.adk.cli", "api_server", "insurance_technical_agent", "--port", "8002", "--host", "0.0.0.0"]
        ports:
        - containerPort: 8002
          name: http
        env:
        - name: GOOGLE_API_KEY
          value: "test_placeholder"
        - name: PORT
          value: "8002"
        - name: HOST
          value: "0.0.0.0"
        - name: POLICY_SERVER_URL
          value: "http://policy-server:8001/mcp"
        - name: MCP_SERVER_URL
          value: "http://policy-server:8001/mcp"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"

---
# ADK Technical Agent Service
apiVersion: v1
kind: Service
metadata:
  name: adk-technical-agent
  namespace: insurance-ai-poc
  labels:
    app: adk-technical-agent
spec:
  type: ClusterIP
  selector:
    app: adk-technical-agent
  ports:
  - port: 8002
    targetPort: 8002
    protocol: TCP
    name: http

---
# ADK Orchestrator Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adk-orchestrator
  namespace: insurance-ai-poc
  labels:
    app: adk-orchestrator
    component: adk-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adk-orchestrator
  template:
    metadata:
      labels:
        app: adk-orchestrator
        component: adk-agent
    spec:
      containers:
      - name: adk-orchestrator
        image: insurance-ai-poc:latest
        imagePullPolicy: IfNotPresent
        workingDir: /app/insurance-adk
        command: ["python", "-m", "google.adk.cli", "api_server", "insurance_orchestrator", "--port", "8003", "--host", "0.0.0.0"]
        ports:
        - containerPort: 8003
          name: http
        env:
        - name: GOOGLE_API_KEY
          value: "test_placeholder"
        - name: PORT
          value: "8003"
        - name: HOST
          value: "0.0.0.0"
        - name: CUSTOMER_SERVICE_URL
          value: "http://adk-customer-service:8000"
        - name: TECHNICAL_AGENT_URL
          value: "http://adk-technical-agent:8002"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"

---
# ADK Orchestrator Service
apiVersion: v1
kind: Service
metadata:
  name: adk-orchestrator
  namespace: insurance-ai-poc
  labels:
    app: adk-orchestrator
spec:
  type: ClusterIP
  selector:
    app: adk-orchestrator
  ports:
  - port: 8003
    targetPort: 8003
    protocol: TCP
    name: http 