apiVersion: v1
kind: Secret
metadata:
  name: llm-api-keys
  namespace: insurance-poc
  labels:
    app: insurance-ai-poc
type: Opaque
stringData:
  OPENROUTER_API_KEY: "${OPENROUTER_API_KEY}"
  PRIMARY_MODEL: "qwen/qwen3-30b-a3b:free"
  FALLBACK_MODEL: "anthropic/claude-3-haiku"
  EMBEDDING_MODEL: "openai/text-embedding-ada-002"
  OPENROUTER_BASE_URL: "https://openrouter.ai/api/v1"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  namespace: insurance-poc
  labels:
    app: insurance-ai-poc
data:
  LOG_LEVEL: "INFO"
  DEBUG: "false"
  PYTHONPATH: "/app"
  PYTHONUNBUFFERED: "1"
  # Service URLs for inter-agent communication
  CUSTOMER_AGENT_URL: "http://customer-agent:8010"
  POLICY_AGENT_URL: "http://policy-agent:8011"
  CLAIMS_DATA_AGENT_URL: "http://claims-agent:8012" 