[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "agents-shared"
version = "1.0.0"
description = "Shared utilities for A2A agents and MCP integration"
dependencies = [
    "fastapi",
    "pydantic",
    "httpx",
    "structlog", 
    "fastmcp",
    "python-jose[cryptography]",
    "passlib[bcrypt]",
    "tenacity",
    "circuitbreaker",
] 