apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-insurance-ui
  namespace: cursor-insurance-ai-poc
  labels:
    app: simple-insurance-ui
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-insurance-ui
  template:
    metadata:
      labels:
        app: simple-insurance-ui
        component: frontend
    spec:
      containers:
      - name: simple-insurance-ui
        image: insurance-ai/simple-ui:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8501
          name: http
        env:
        - name: CLAIMS_AGENT_URL
          value: "http://claims-agent:8000"
        - name: STREAMLIT_SERVER_PORT
          value: "8501"
        - name: STREAMLIT_SERVER_ADDRESS
          value: "0.0.0.0"
        - name: STREAMLIT_SERVER_HEADLESS
          value: "true"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: simple-insurance-ui
  namespace: cursor-insurance-ai-poc
  labels:
    app: simple-insurance-ui
    component: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 8501
    targetPort: 8501
    protocol: TCP
    name: http
  selector:
    app: simple-insurance-ui 