[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "technical-agents"
version = "1.0.0"
description = "Technical capability agents (Data, Notification, Integration)"
dependencies = [
    "fastapi",
    "uvicorn", 
    "structlog",
    "httpx",
    "fastmcp",
    "prometheus-client",
] 